name: kics-github-action

on:
  push:
    branches: [main]

jobs:
  kics-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run KICS Scan
        uses: checkmarx/kics-action@v1.5
        with:
#           token: ${{ secrets.GITHUB_TOKEN }}
          path: "./Dockerfile"
          ignore_on_exit: results
#           enable_comments: true
          output_path: ./results
          output_formats: json,html
          type: dockerfile
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./results
