name: Sync Back to Develop

on:
  push:
    branches: [master]

jobs:
  sync-release:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - uses: actions/checkout@v2
      - name: Sync Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "master"
          destination_branch: "main"                
          pr_title: "update(main): sync master to main"
          pr_body: ":crown: *An automated PR*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "update(main): sync master to main"
          token: ${{ secrets.KICS_BOT_PAT }}
          commit-message: "update(main): sync master to main"
          branch: master
          base: main
