name: Sync Back to Develop

on:
  push:
    branches: [master]

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "rafaela-soares/queries"
          source_branch: "master"
          destination_repo: "rafaela-soares/queries"
          destination_branch: "main"
