name: Sync Back to Develop

on:
  push:
    branches: [master]

jobs:
  sync-release:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Sync Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "master"
          destination_branch: "main"                 
          pr_title: "update(main): sync master to main" 
          pr_body: ":crown: *An automated PR*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
