name: Sync Back to Develop

on:
  push:
    branches: [master]

jobs:
  sync-release:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "update(main): sync master to main"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update(main): sync master to main"
          branch: master
          base: main
